# Importing Numpy library

In [1]:
import numpy as np

### Basic Array Creation

In [2]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
a = [1,2,3.5,"Hello"]
a

[1, 2, 3.5, 'Hello']

In [4]:
np.array(a)

array(['1', '2', '3.5', 'Hello'], dtype='<U32')

Vectors: Vectors are one-dimensional.


Matrix: A matrix is are two-dimensional.

In [5]:
list = [[1,2,3],[4,5,6],[7,8,9]]
list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
arr2 = np.array(list)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array Generation Function

In [7]:
arr3 = np.arange(1,11)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr4 = np.zeros((3,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr5 = np.ones((4,5))
arr5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
arr6 = np.linspace(1,2,10)
arr6

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

linspace(): It means linear space between the intervals

### Random Generation Function

In [11]:
arr7 = np.random.rand(10)
arr7

array([0.31910675, 0.15230088, 0.81670807, 0.84774706, 0.01178027,
       0.05846023, 0.93914218, 0.0624845 , 0.48010735, 0.35810828])

.random.rand(): It gives the normalized value between 0 and 1.

In [13]:
arr8 = np.random.randn(10)
arr8

array([-0.48237925,  2.51233113, -0.66791057,  0.48700624, -0.04345737,
       -2.38592961, -1.30128706, -0.76811515,  0.12946448,  1.39034974])

.random.randn(): It gives the standardization value between -3 to 3

In [15]:
arr9 = np.random.randint(1,10,5)
arr9

array([5, 1, 9, 6, 8])

.random.randint(): It gives a random integer value. 

### Array Attributes

Attributes are kind of variables defined inside the class.

Method are functions define inside a class. 

In [16]:
arr10 = np.array(list)
arr10

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr10.shape

(3, 3)

.shape: It shows the number of rows and columns present in the array.

In [18]:
arr10.size

9

.size: It shows the elements presnt in the array.

In [19]:
arr10.dtype

dtype('int32')

.dtype: It shows the datatype of the array.

### Array Methods

In [25]:
arr10

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr10.min()

1

.min(): It shows the minimum value present in the array.

In [21]:
arr10.max()

9

.max(): It shows the maximum value present in the array.

In [22]:
arr10.sum()

45

.sum(): It shows the sum of the value present in the array.

In [23]:
np.sum(arr10,axis=0)

array([12, 15, 18])

In [24]:
np.sum(arr10,axis=1)

array([ 6, 15, 24])

np.sum(): It shows the sum of the array along with rows and columns based on the axis value.
0 -> columns and 1 -> rows.

In [27]:
arr10.mean()

5.0

.mean(): It shows the mean value of the array

In [28]:
arr10.std()

2.581988897471611

.std(): It provide the standard deviation value of the array.

In [29]:
arr10.argmax()

8

.argmax(): It shows the maximum index value of the array element.

In [30]:
arr10.argmin()

0

.argmin(): It shows the minimum index value of the array element.

### Reshaping And Resizing

In [31]:
arr11 = np.arange(1,31)
arr11

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [32]:
arr11.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

.reshape(): It reshapes the array into a matrix with rows and columns.

In [34]:
arr12 = arr11.reshape(6,5)
arr12

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])