# Importing NumPy library

In [1]:
import numpy as np

## **Array Operations**

### 1. Arithmetic Operations

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [3]:
sum = a1 + a2
sum

array([ 7,  9, 11, 13, 15])

Performing the arithmetic operation, the size of both arrays must be the same 

In [4]:
difference = a2 - a1
difference

array([5, 5, 5, 5, 5])

In [5]:
product = a1 * a2
product

array([ 6, 14, 24, 36, 50])

In [6]:
divide = a2 / a1
divide

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [7]:
floor_division = a2 // a1
floor_division

array([6, 3, 2, 2, 2])

### 2. Broadcasting

In [8]:
list = [10,20,30,40,50]
arr = np.array(list)
arr

array([10, 20, 30, 40, 50])

In [9]:
arr + 10

array([20, 30, 40, 50, 60])

In [10]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [11]:
arr3 = arr2 + 10
arr3

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

### 3. Deep and Shallow copy

In [12]:
arr4 = np.arange(1,21)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [13]:
slice = arr4[:5]
slice = slice*10
slice

array([10, 20, 30, 40, 50])

In [14]:
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [15]:
arr5 = arr4.copy()
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
arr5[0] = 99
arr5

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### 4. Matrix Operations

In [19]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [20]:
A

array([[1, 2],
       [3, 4]])

In [21]:
B

array([[5, 6],
       [7, 8]])

In [22]:
arr5 = A @ B
arr5

array([[19, 22],
       [43, 50]])

@ symbol is used for the dot product of the two matrices

In [24]:
arr6 = np.dot(A,B)
arr6

array([[19, 22],
       [43, 50]])

np.dot(): It is also used for the dot product of two matrices

In [25]:
arr7 = arr6.T
arr7

array([[19, 43],
       [22, 50]])

.T: is used for the transpose of the matrix

## Advanced Array Manipulation

### 1. Stacking Array

In [26]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [27]:
a,b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [28]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### 2. Splitting Array

In [32]:
arr8 = np.arange(16).reshape(4,4)
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
arr9 = np.hsplit(arr8,2)
arr9

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [38]:
for i in arr9:
    print(i)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [39]:
arr10 = np.vsplit(arr8,2)
arr10

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [40]:
for i in arr10:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
