# Import NumPy Library

In [1]:
import numpy as np

#### Valid Sudoku

In [14]:
sudoku = np.array([
         [5,3,4,6,7,8,9,1,2],
         [6,7,2,1,9,5,3,4,8],
         [1,9,8,3,4,2,5,6,7],

         [8,5,9,7,6,1,4,2,3],
         [4,2,6,8,5,3,7,9,1],
         [7,1,3,9,2,4,8,5,6],

         [9,6,1,5,3,7,2,8,4],
         [2,8,7,4,1,9,6,3,5],
         [3,4,5,2,8,6,1,7,9]
    
])

In [28]:
check_row = np.sum(sudoku,axis=1)

In [29]:
check_row

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [26]:
for i in check_row:
    if i != 45:
        print("Sudoku is not valid for rows")
        break
else:
    print("Sudoku is valid for rows")

Sudoku is valid for rows


In [23]:
check_column = np.sum(sudoku,axis=0)

In [30]:
check_column

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [27]:
for i in check_column:
    if i != 45:
        print("Sudoku is not valid for columns")
        break
else:
    print("Sudoku is valid for column")


Sudoku is valid for column


In [31]:
sudoku[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [32]:
sudoku[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [33]:
sudoku[0:3,6:]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [36]:
sudoku

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [37]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = sudoku[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


### General Questions

In [38]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
        [18,85,78],  #Student 1
        [19,92,88],  #Student 2
        [17,76,95],  #Student 3
        [18,65,70],  #Student 4
        [20,90,85]   #Student 5
])

In [42]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [43]:
#Find the average age of students.
np.mean(data[:,0])

18.4

In [44]:
#Extract the Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [46]:
#Find the highest Science mark.
np.max(data[:,2])

95

In [48]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]

array([[19, 92, 88]])

In [49]:
#Increase the Math marks of all students by 5.
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [53]:
#Find how many students are younger than 19.
data[data[:,0] < 19]

array([[18, 90, 78],
       [17, 81, 95],
       [18, 70, 70]])

In [54]:
len(data[data[:,0] < 19])

3

In [57]:
#Calculate the average marks in each subject(column-wise mean).
data[:,1:]

array([[90, 78],
       [97, 88],
       [81, 95],
       [70, 70],
       [95, 85]])

In [58]:
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [60]:
#Get the data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [63]:
#Replace all science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])