# Importing Numpy Library

In [2]:
import numpy as np

## NumPy Indexing and Slicing of vectors

In [4]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[7]

18

In [6]:
arr[1:5]

array([12, 13, 14, 15])

array[start:end:steps]: It is the method of slicing where we give the starting index, ending index, and steps.

## NumPy Indexing and Slicing of matrix

In [8]:
arr2 = np.arange(1,31).reshape(6,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [11]:
arr2[0,4]

5

In [13]:
slice = arr2[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [15]:
slice_2 = arr2[3:,3:]
slice_2

array([[19, 20],
       [24, 25],
       [29, 30]])

In [18]:
slice_3 = arr2[:,2]
slice_3

array([ 3,  8, 13, 18, 23, 28])

## Boolean Indexing

In [19]:
arr3 = np.arange(11,21)
arr3

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [20]:
bool_index = arr3%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [22]:
arr4 = arr3[bool_index]
arr4

array([12, 14, 16, 18, 20])